# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 16:47
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(upload_to='debug/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Thumbnail Upload')),
                ('video_file', models.FileField(upload_to='debug/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Video Upload')),
                ('cuisine_type', models.CharField(choices=[('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('ITALIAN', 'ITALIAN'), ('KOREAN', 'KOREAN'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('PAKISTANI', 'PAKISTANI'), ('GREEK', 'GREEK'), ('JAPANESE', 'JAPANESE'), ('AMERICAN', 'AMERICAN'), ('BRITISH', 'BRITISH')], default='CHINESE', max_length=10)),
                ('title', models.CharField(max_length=50, verbose_name='Recipe Name')),
                ('description', models.CharField(max_length=300)),
                ('taste', models.IntegerField(default=0)),
                ('difficulty', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taste', models.CharField(max_length=10)),
                ('difficulty', models.CharField(max_length=10)),
                ('price', models.CharField(max_length=10)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookflixapp.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookflixapp.Recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('preferred_cuisine', models.CharField(choices=[('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('ITALIAN', 'ITALIAN'), ('KOREAN', 'KOREAN'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('PAKISTANI', 'PAKISTANI'), ('GREEK', 'GREEK'), ('JAPANESE', 'JAPANESE'), ('AMERICAN', 'AMERICAN'), ('BRITISH', 'BRITISH')], default='CHINESE', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookflixapp.Recipe'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
