# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 19:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='thumbnail',
            field=models.FileField(upload_to='debug/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpeg', 'jpg'])], verbose_name='Thumbnail Upload'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='video_file',
            field=models.FileField(upload_to='debug/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])], verbose_name='Video Upload'),
        ),
    ]
