# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0002_auto_20190308_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisine',
            field=models.CharField(max_length=10),
        ),
    ]
