# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-28 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0004_auto_20190228_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
