# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0005_auto_20190228_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='picture_width', max_length=255, upload_to=None, width_field='picture_height'),
        ),
    ]
