# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 14:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0005_auto_20190311_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='cuisine',
            new_name='preferred_cuisine',
        ),
    ]
