# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-08 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0005_auto_20190305_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
