# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-11 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0006_auto_20190311_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisine',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
