# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0009_auto_20190311_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cookflixapp.Recipe'),
        ),
    ]
