# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0009_auto_20190311_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisine',
            field=models.CharField(choices=[('chinese', 'CHINESE'), ('indian', 'INDIAN'), ('italian', 'ITALIAN'), ('korean', 'KOREAN'), ('spanish', 'SPANISH'), ('french', 'FRENCH'), ('pakistani', 'PAKISTANI'), ('greek', 'GREEK'), ('japanese', 'JAPANESE'), ('american', 'AMERICAN'), ('british', 'BRITISH')], default='chinese', max_length=50),
        ),
    ]
