# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0010_auto_20190318_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(choices=[('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('ITALIAN', 'ITALIAN'), ('KOREAN', 'KOREAN'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('PAKISTANI', 'PAKISTANI'), ('GREEK', 'GREEK'), ('JAPANESE', 'JAPANESE'), ('AMERICAN', 'AMERICAN'), ('BRITISH', 'BRITISH')], default='CHINESE', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisine',
            field=models.CharField(choices=[('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('ITALIAN', 'ITALIAN'), ('KOREAN', 'KOREAN'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('PAKISTANI', 'PAKISTANI'), ('GREEK', 'GREEK'), ('JAPANESE', 'JAPANESE'), ('AMERICAN', 'AMERICAN'), ('BRITISH', 'BRITISH')], default='CHINESE', max_length=50),
        ),
    ]
