# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 13:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookflixapp', '0011_merge_20190319_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookflixapp.Recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cuisine_type',
            field=models.CharField(choices=[('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('ITALIAN', 'ITALIAN'), ('KOREAN', 'KOREAN'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('PAKISTANI', 'PAKISTANI'), ('GREEK', 'GREEK'), ('JAPANESE', 'JAPANESE'), ('AMERICAN', 'AMERICAN'), ('BRITISH', 'BRITISH')], default='CHINESE', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_cuisine',
            field=models.CharField(choices=[('CHINESE', 'CHINESE'), ('INDIAN', 'INDIAN'), ('ITALIAN', 'ITALIAN'), ('KOREAN', 'KOREAN'), ('SPANISH', 'SPANISH'), ('FRENCH', 'FRENCH'), ('PAKISTANI', 'PAKISTANI'), ('GREEK', 'GREEK'), ('JAPANESE', 'JAPANESE'), ('AMERICAN', 'AMERICAN'), ('BRITISH', 'BRITISH')], default='CHINESE', max_length=50),
        ),
    ]
